# 构建阶段
FROM php:7.2-fpm-alpine AS builder

LABEL org.opencontainers.image.authors="XiaoYu <1765841705@qq.com>"

ARG PHP_EXTENSIONS_72
ARG CONTAINER_PACKAGE_URL
ARG COMPOSER_DOWNLOAD_URL
ARG COMPOSER_IMAGE_URL
ARG TZ

# 引入 install-php-extensions 脚本
ADD extensions/install-php-extensions /usr/local/bin/
RUN chmod +x /usr/local/bin/install-php-extensions

# 更新包索引，升级系统
RUN apk update && apk upgrade \
    # 资源替换 更换镜像
    && if [ -n "${CONTAINER_PACKAGE_URL}" ]; then sed -i "s/dl-cdn.alpinelinux.org/${CONTAINER_PACKAGE_URL}/g" /etc/apk/repositories; fi \
    # 修改时间
    && apk add --no-cache --virtual .build-deps tzdata \
    && if [ -n "${TZ}" ]; then cp -r "/usr/share/zoneinfo/${TZ}" /etc/localtime && echo "${TZ}" > /etc/timezone; fi \
    # 安装依赖和 PHP 扩展
    && install-php-extensions $(echo ${PHP_EXTENSIONS_72} | tr ',' ' ') \
    # 安装 Composer
    && curl -sS ${COMPOSER_DOWNLOAD_URL} | php \
    && chmod +x composer.phar \
    && mv composer.phar /usr/local/bin/composer \
    # 替换 Composer 镜像
    && if [ -n "${COMPOSER_IMAGE_URL}" ]; then composer config -g repo.packagist composer ${COMPOSER_IMAGE_URL}; fi \
    # 安装 supervisor
    && apk add --no-cache supervisor \
    && apk del .build-deps

# 修复 iconv 扩展问题
RUN apk add --no-cache --repository https://${CONTAINER_PACKAGE_URL}/alpine/v3.13/community gnu-libiconv=1.15-r3
ENV LD_PRELOAD /usr/lib/preloadable_libiconv.so php

CMD ["supervisord", "-c", "/etc/supervisord.conf", "-n"]