# 测试失败的容器
name: Test Docker image

on:
  workflow_dispatch: # 手动触发工作流程
  pull_request:
    branches:
      - main  # 在拉取请求合并到 main 分支时触发
  schedule:
    - cron: '0 0 * * *' # 每天 0点（UTC），相当于中国时间每天凌晨8点
  push:
    branches:
      - main  # 在推送到 main 分支时触发

jobs:
  build_php_images:
    strategy:
      fail-fast: false  # 让所有任务运行完成，失败不会中断其他任务
      matrix:
        php_version:
          - php81
          - php82
          - php83
          - php84  # 分别测试不同的 PHP 版本
    runs-on: ubuntu-latest
    name: Build and Test ${{ matrix.php_version }} Docker Image

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4  # 检出代码

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3  # 设置 Buildx 环境

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3  # 设置 QEMU 以支持多架构

      - name: Load .env file
        run: |
          if [ -f .github/workflows/.env ]; then
            # 只导出符合格式的环境变量
            grep -v '^#' .github/workflows/.env | grep '=' | while IFS= read -r line; do
              # 忽略以 '=' 开头的行和空行
              if [[ "$line" =~ ^[^=]+=.+$ ]]; then
                export "$line"
              fi
            done
          fi
        shell: /usr/bin/bash -e {0}  # 加载 .env 文件，导出符合格式的环境变量

      - name: Override PHP extensions in .env file
        run: |
          version_number=$(echo "${{ matrix.php_version }}" | sed 's/php//')
          if [ "$version_number" = "84" ]; then
            echo "PHP_EXTENSIONS_${version_number}=swoole,phalcon" >> .github/workflows/.env
          else
            echo "PHP_EXTENSIONS_${version_number}=phalcon" >> .github/workflows/.env
          fi

      - name: Build Docker image for ${{ matrix.php_version }}
        run: docker compose -f compose.sample.yml --env-file .github/workflows/.env build ${{ matrix.php_version }}
        env:
          DOCKER_BUILDKIT: 1
          COMPOSE_DOCKER_CLI_BUILD: 1
          PHP_EXTENSIONS_81: phalcon
          PHP_EXTENSIONS_82: phalcon
          PHP_EXTENSIONS_83: phalcon
          PHP_EXTENSIONS_84: phalcon

      - name: Verify ${{ matrix.php_version }} Docker image
        run: |
          docker compose -f compose.sample.yml --env-file .github/workflows/.env up -d ${{ matrix.php_version }}
          docker compose -f compose.sample.yml --env-file .github/workflows/.env exec ${{ matrix.php_version }} php -v  # 验证 PHP 版本
          docker compose -f compose.sample.yml --env-file .github/workflows/.env exec ${{ matrix.php_version }} php -m  # 验证 PHP 扩展